CREATE TABLE "appointments" (
	"id" text PRIMARY KEY NOT NULL,
	"full_name" text NOT NULL,
	"nid" text DEFAULT '' NOT NULL,
	"age" text NOT NULL,
	"weight" text DEFAULT '' NOT NULL,
	"gender" text NOT NULL,
	"religion" text NOT NULL,
	"duration" text NOT NULL,
	"previous_treatment" boolean DEFAULT false NOT NULL,
	"previous_treatment_details" text DEFAULT '' NOT NULL,
	"service_mode" text NOT NULL,
	"session_format" text NOT NULL,
	"treatment_type_key" text NOT NULL,
	"treatment_type_label" text NOT NULL,
	"sub_services" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"preferred_date" text NOT NULL,
	"preferred_time" text NOT NULL,
	"address" text NOT NULL,
	"phone" text NOT NULL,
	"whatsapp" text DEFAULT '' NOT NULL,
	"problem" text NOT NULL,
	"payment_method" text NOT NULL,
	"transaction_id" text NOT NULL,
	"payment_timestamp" text NOT NULL,
	"source" text DEFAULT 'web' NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
