import { boolean, jsonb, pgTable, text, timestamp } from 'drizzle-orm/pg-core';

export const appointments = pgTable('appointments', {
  id: text('id').primaryKey(),
  fullName: text('full_name').notNull(),
  nid: text('nid').notNull().default(''),
  age: text('age').notNull(),
  weight: text('weight').notNull().default(''),
  gender: text('gender').notNull(),
  religion: text('religion').notNull(),
  duration: text('duration').notNull(),
  previousTreatment: boolean('previous_treatment').notNull().default(false),
  previousTreatmentDetails: text('previous_treatment_details').notNull().default(''),
  serviceMode: text('service_mode').notNull(),
  sessionFormat: text('session_format').notNull(),
  treatmentTypeKey: text('treatment_type_key').notNull(),
  treatmentTypeLabel: text('treatment_type_label').notNull(),
  subServices: jsonb('sub_services').notNull().default([]),
  preferredDate: text('preferred_date').notNull(),
  preferredTime: text('preferred_time').notNull(),
  address: text('address').notNull(),
  phone: text('phone').notNull(),
  whatsapp: text('whatsapp').notNull().default(''),
  problem: text('problem').notNull(),
  paymentMethod: text('payment_method').notNull(),
  transactionId: text('transaction_id').notNull(),
  paymentTimestamp: text('payment_timestamp').notNull(),
  source: text('source').notNull().default('web'),
  status: text('status').notNull().default('pending'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});
